Revert "[Structured metrics] Rearrange build files"
This reverts commit cbe2538725a29c5e644f2e87d9f979dca6d68af1.

Reason for revert:Breaks compile on chromeos-amd64-generic-rel.

"./../components/metrics/structured/key_data.cc:18:10: fatal error: 'tools/metrics/structured/structured_events.h' file not found
#include "tools/metrics/structured/structured_events.h""

Original change's description:
> [Structured metrics] Rearrange build files
> 
> Currently, the generated classes for each event are created under the
> //tools/metrics/structured target. I don't think this is the intended
> use of the tools directory, because chrome targets explicitely can't
> depend on it, and so can't access the generated events.
> 
> This CL moves the codegen targets to //components/metrics/structured,
> which is accessible from chrome (and just makes more sense).
> 
> Bug: 1016655
> Change-Id: I6a295486a3dad094b44db67d70408c8629728bcc
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2029531
> Commit-Queue: Tony Yeoman <tby@chromium.org>
> Auto-Submit: Tony Yeoman <tby@chromium.org>
> Reviewed-by: Jia Meng <jiameng@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#736753}

TBR=jiameng@chromium.org,tby@chromium.org

Change-Id: Ic631a141d60e35e5a224d64d355ca1662e4c4c80
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1016655
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2029509
Reviewed-by: Ioana Pandele <ioanap@chromium.org>
Commit-Queue: Ioana Pandele <ioanap@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#736774}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 561b3a08640909d54cc95d53e63e0c77a8268d88